package com.payments.validator.model;

public enum ValidationStatus {
    PASS,
    PASS_WITH_WARNINGS,
    FAIL_PARSE,
    FAIL_MANDATORY_FIELD,
    FAIL_CONDITIONAL_FIELD,
    FAIL_FIELD_FORMAT,
    FAIL_FIELD_VALUE,
    FAIL_CROSS_FIELD,
    FAIL_PROHIBITED_FIELD,
    FAIL_SCENARIO_CONFLICT,
    FAIL_RULE_CONFIGURATION,
    INDETERMINATE
}
